DROP DATABASE IF EXISTS BANCO;

CREATE DATABASE BANCO;

USE BANCO;

CREATE TABLE ESTADO(
ID INT NOT NULL AUTO_INCREMENT
,NOME VARCHAR(255) NOT NULL UNIQUE 
,SIGLA CHAR(2) NOT NULL UNIQUE 
,STATUS CHAR(1) DEFAULT 'A' NOT NULL 
,CONSTRAINT PK_ESTADO PRIMARY KEY (ID) 
);

CREATE TABLE CIDADE(
ID INT NOT NULL AUTO_INCREMENT
,NOME VARCHAR(255) NOT NULL UNIQUE 
,ESTADO_ID INT NOT NULL 
,STATUS CHAR(1) DEFAULT 'A' NOT NULL
,CONSTRAINT PK_CIDADE PRIMARY KEY (ID) 
,CONSTRAINT FK_CID_EST FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ID)
,CONSTRAINT CIDADE_UNICO UNIQUE(NOME,ESTADO_ID)
);

CREATE TABLE CLIENTE(
ID INT NOT NULL AUTO_INCREMENT
,NOME VARCHAR(255) NOT NULL UNIQUE 
,DOCUMENTO VARCHAR(18) NOT NULL UNIQUE
,TIPO CHAR NOT NULL 
,STATUS CHAR(1) DEFAULT 'A' NOT NULL
,CIDADE_ID INT NOT NULL 
,CONSTRAINT PK_CLIENTE PRIMARY KEY (ID) 
,CONSTRAINT FK_CLI_CID FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID)
);

CREATE TABLE FUNCIONARIO(
ID INT NOT NULL AUTO_INCREMENT
,NOME VARCHAR(255) NOT NULL UNIQUE 
,CPF VARCHAR(14) NOT NULL UNIQUE
,STATUS CHAR(1) DEFAULT 'A' NOT NULL
,CIDADE_ID INT NOT NULL 
,CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID) 
,CONSTRAINT FK_FUN_CID FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID)
);

CREATE TABLE PRODUTO(
ID INT NOT NULL AUTO_INCREMENT
,NOME VARCHAR(255) NOT NULL UNIQUE 
,PRECO_V DOUBLE NOT NULL 
,ESTOQUE INT NOT NULL 
,STATUS CHAR(1) DEFAULT 'A' NOT NULL
,CONSTRAINT PK_PRODUTO PRIMARY KEY (ID) 
);

CREATE TABLE VENDA(
ID INT NOT NULL AUTO_INCREMENT 
,DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
,FUNCIONARIO_ID INT NOT NULL 
,CLIENTE_ID INT NOT NULL 
,CONSTRAINT PK_VENDA PRIMARY KEY (ID) 
,CONSTRAINT FK_VEN_FUN FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO (ID)
,CONSTRAINT FK_VEN_CLI FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
);

CREATE TABLE IVENDA(
PRODUTO_ID INT NOT NULL
,VENDA_ID INT NOT NULL 
,QUANTIDADE INT NOT NULL 
,CONSTRAINT PK_IVENDA PRIMARY KEY (PRODUTO_ID,VENDA_ID) 
,CONSTRAINT FK_IVEN_PROD FOREIGN KEY (PRODUTO_ID) REFERENCES FUNCIONARIO (ID)
,CONSTRAINT FK_IVEN_VEN FOREIGN KEY (VENDA_ID) REFERENCES FUNCIONARIO (ID)
);

INSERT INTO ESTADO (NOME,SIGLA) VALUES ('PARANÁ','PR'),('SÃO PAULO','SP'),('MATO GROSSO','MT');
INSERT INTO CIDADE (NOME,ESTADO_ID) VALUES ('PARANAVAÍ',1),('MARINGÁ',1),('BAURU',2),('NAVIRAÍ',3),('SÃO PAULO',2);
INSERT INTO CLIENTE (NOME,DOCUMENTO,TIPO,CIDADE_ID) VALUES ('ROGÉRIO GONÇALEZ','897.852.741-65','F',1),('PAULA SILVA','147.789.369-74','F',1),('OTÁVIO SILVA','852.789.321-12','F',3),('JOANA FERNANDEZ','489.123.687-12','F',2),('MARIANA JOAQUINA','129.651.258-74','F',2);
INSERT INTO FUNCIONARIO (NOME,CPF,CIDADE_ID) VALUES ('RICARDO PEREIRA','897.852.741-65',1),('JOÃO ANTUNEZ','147.789.369-74',1),('CAROLINA FERRAZ','852.789.321-12',3),('FERNANDA CORTEZ','489.123.687-12',2);
INSERT INTO PRODUTO (NOME,PRECO_V,ESTOQUE) VALUES ('REFRIGERANTE',4,200),('SALGADO',5,35),('SANDUICHE',8,15);

